services:
  - type: web
    name: mathmandala-upload
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn upload_server.py:app --host 0.0.0.0 --port 10000
    envVars: []
